# Generated by Django 3.2.5 on 2021-07-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
    ]
