# Generated by Django 3.2.5 on 2021-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('form', models.IntegerField()),
                ('enrollment_year', models.IntegerField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
