# Generated by Django 3.2.5 on 2021-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='primary_contact_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_contact_email',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_contact_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
