# Generated by Django 3.2.5 on 2021-07-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210728_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='primary_contact_name',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondary_contact_email',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondary_contact_name',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
