# Generated by Django 3.2.5 on 2021-07-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210728_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='primary_contact_email',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
