# Generated by Django 3.2.5 on 2021-08-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0004_student_primary_contact_email'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_awarded', models.DecimalField(decimal_places=1, max_digits=3)),
                ('assignment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'marks',
                'unique_together': {('assignment_id', 'student_id')},
            },
        ),
    ]
