# Generated by Django 3.2.5 on 2021-08-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_teacher_id_assignment_teacher'),
        ('students', '0004_student_primary_contact_email'),
        ('marks', '0002_auto_20210814_2202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('assignment_id', 'student_id')},
        ),
    ]
