# Generated by Django 3.2.6 on 2021-08-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_marks_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark_awarded',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
