# Generated by Django 3.2.5 on 2021-08-25 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_primary_contact_email'),
        ('classes', '0006_rename_student_studentclasses_student_id'),
        ('assignments', '0008_alter_assignment_teacher'),
        ('marks', '0005_alter_marks_mark_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
