# Generated by Django 3.2.5 on 2021-07-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210727_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(default='Ochse', max_length=256),
            preserve_default=False,
        ),
    ]
