# Generated by Django 3.2.5 on 2021-10-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('colour', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'houses',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.house'),
        ),
    ]
