# Generated by Django 3.2.6 on 2021-10-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211001_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='id',
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
