# Generated by Django 3.2.6 on 2021-10-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211002_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.house'),
        ),
    ]
