# Generated by Django 3.2.6 on 2021-10-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house',
        ),
    ]
