# Generated by Django 3.2.6 on 2021-10-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='house',
            new_name='house_name',
        ),
    ]
