# Generated by Django 3.2.6 on 2021-10-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_house_user_house_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='house_name',
            new_name='house',
        ),
    ]
