# Generated by Django 3.2.5 on 2021-08-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentclasses',
            table='student_classes',
        ),
    ]
