# Generated by Django 3.2.6 on 2021-08-14 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasses',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentclasses',
            name='graduation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
