# Generated by Django 3.2.6 on 2021-08-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210815_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclasses',
            old_name='student',
            new_name='student_id',
        ),
    ]
