# Generated by Django 3.2.5 on 2021-10-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_primary_contact_email'),
        ('classes', '0006_rename_student_studentclasses_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasses',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
