# Generated by Django 3.2.5 on 2021-10-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_primary_contact_email'),
        ('classes', '0008_alter_studentclasses_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasses',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='studentclasses',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
