# Generated by Django 3.2.5 on 2021-08-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
