# Generated by Django 3.2.6 on 2021-08-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignment_max_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_assigned',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_due',
            field=models.DateField(),
        ),
    ]
