# Generated by Django 3.2.5 on 2021-10-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_studentclasses_student_id'),
        ('teachers', '0002_teacherclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclasses',
            name='class_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='teacherclasses',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
