# Generated by Django 3.2.5 on 2021-10-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_studentclasses_class_id'),
        ('teachers', '0003_auto_20211003_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclasses',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='teacherclasses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
