# Generated by Django 3.2.6 on 2021-08-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_teacherclasses'),
        ('students', '0004_student_primary_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default=None, max_length=256)),
                ('assigning_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'dots',
            },
        ),
    ]
